#!/bin/bash

gcc -o dec_client dec_client.c
gcc -o enc_client enc_client.c
gcc -o dec_server dec_server.c
gcc -o dec_server dec_server.c
gcc -o keygen keygen.c
lsof -t -i :57171 | xargs kill -9
lsof -t -i :57172 | xargs kill -9

enc_server 57171 &
dec_server 57172 &


